# Generated by Django 5.2.6 on 2025-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonphoto',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='missingpersonphoto',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
